{{- if and (eq .Values.mode "file") .Values.file.inlineConfig (not .Values.file.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" (include "ferrum-gateway.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ferrum-gateway.labels" . | nindent 4 }}
data:
  {{ .Values.file.fileName | default "config.yaml" }}: |
    {{- .Values.file.inlineConfig | nindent 4 }}
{{- end }}
