//! Performance-only HBONE E2E fixture for `tests/performance/mesh-hbone-e2e`.
//!
//! Production mesh materialization builds a [`GatewayConfig`] in-process
//! (including reserved `mesh.*` transport tags) and feeds it to
//! [`ferrum_edge::modes::file::serve`] / `ProxyState`. Operator file/admin
//! admission (`GatewayConfig::validate_operator_provided_fields`) must keep
//! rejecting those tags.
//!
//! This binary is that trusted projection boundary for the hosted HBONE
//! baseline harness only. It:
//! - constructs the fixture topology internally (not from operator YAML)
//! - normalizes the config the way mesh projection does
//! - pre-binds the requested proxy/admin listeners
//! - loads generated gateway SVID / trust-bundle paths into [`EnvConfig`]
//! - supplies an explicit admin JWT manager
//! - installs the process rustls provider
//! - runs the real HBONE pool through `file::serve` until SIGINT/SIGTERM or a
//!   listener failure
//!
//! It is **not** a general-purpose trusted config loader, file-loader escape
//! hatch, env bypass, or allowlist. There is no config-file path argument.

#[cfg(not(windows))]
#[global_allocator]
static GLOBAL: tikv_jemallocator::Jemalloc = tikv_jemallocator::Jemalloc;

use std::net::SocketAddr;
use std::path::{Path, PathBuf};
use std::time::Duration;

use anyhow::{Context, bail};
use clap::Parser;
use ferrum_edge::admin::jwt_auth::{JwtConfig, JwtManager};
use ferrum_edge::config::types::GatewayConfig;
use ferrum_edge::config::{BackendAllowIps, BackendEgressPolicy, EnvConfig, OperatingMode};
use ferrum_edge::modes::file::{ServeOptions, serve};
use jsonwebtoken::Algorithm;
use tokio::net::TcpListener;
use tokio::sync::watch;
use uuid::Uuid;

#[derive(Parser, Debug)]
#[command(
    name = "hbone_perf_fixture",
    about = "Performance-only trusted-projection HBONE fixture. Not a production gateway.",
    disable_help_subcommand = true
)]
struct Args {
    /// Plaintext proxy listen port (pre-bound; fail closed if unavailable).
    #[arg(long)]
    proxy_http_port: u16,
    /// Plaintext admin listen port (pre-bound; fail closed if unavailable).
    #[arg(long)]
    admin_http_port: u16,
    /// Sidecar HBONE listener host stamped onto the projected upstream target.
    #[arg(long, default_value = "127.0.0.1")]
    sidecar_host: String,
    /// Sidecar HBONE listener port (`mesh.hbone_port` and dial port).
    #[arg(long)]
    sidecar_port: u16,
    /// Gateway SVID certificate path generated by the harness.
    #[arg(long)]
    svid_cert: PathBuf,
    /// Gateway SVID private-key path generated by the harness.
    #[arg(long)]
    svid_key: PathBuf,
    /// Trust-bundle path generated by the harness.
    #[arg(long)]
    trust_bundle: PathBuf,
    /// Gateway SPIFFE ID matching the generated SVID.
    #[arg(long)]
    spiffe_id: String,
    /// Tracing filter (stderr). Keep `error` for baseline collection.
    #[arg(long, default_value = "error")]
    log_level: String,
}

fn main() -> anyhow::Result<()> {
    ferrum_edge::fips::install_crypto_provider()
        .map_err(|err| anyhow::anyhow!("failed to initialize the cryptographic provider: {err}"))?;

    let args = Args::parse();
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::EnvFilter::new(&args.log_level))
        .with_writer(std::io::stderr)
        .init();

    let runtime = tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()
        .context("failed to build tokio runtime")?;
    runtime.block_on(run(args))
}

async fn run(args: Args) -> anyhow::Result<()> {
    validate_identity_paths(&args)?;
    require_private_backend_allow_ips()?;

    let config = projected_hbone_config(&args.sidecar_host, args.sidecar_port)?;

    let proxy_http = bind_loopback(args.proxy_http_port).await.with_context(|| {
        format!(
            "failed to bind proxy HTTP listener on {}",
            args.proxy_http_port
        )
    })?;
    let admin_http = bind_loopback(args.admin_http_port).await.with_context(|| {
        format!(
            "failed to bind admin HTTP listener on {}",
            args.admin_http_port
        )
    })?;

    let jwt_secret = format!("hbone-perf-fixture-jwt-{}", Uuid::new_v4());
    let jwt_issuer = "ferrum-edge-hbone-perf-fixture".to_string();
    let jwt_manager = JwtManager::new(JwtConfig {
        secret: jwt_secret.clone(),
        issuer: jwt_issuer.clone(),
        audience: None,
        max_ttl_seconds: 3600,
        algorithm: Algorithm::HS256,
    });

    let mut env_config = EnvConfig::default();
    env_config.mode = OperatingMode::File;
    env_config.log_level = args.log_level;
    env_config.proxy_bind_address = "127.0.0.1".into();
    env_config.admin_bind_address = "127.0.0.1".into();
    env_config.proxy_http_port = args.proxy_http_port;
    env_config.proxy_https_port = 0;
    env_config.admin_http_port = args.admin_http_port;
    env_config.admin_https_port = 0;
    env_config.admin_jwt_secret = Some(jwt_secret);
    env_config.admin_jwt_issuer = jwt_issuer;
    env_config.pool_warmup_enabled = true;
    env_config.backend_allow_ips = BackendEgressPolicy::from_allow_ips(BackendAllowIps::Private);
    env_config.gateway_svid_cert_path = Some(path_to_string(&args.svid_cert, "--svid-cert")?);
    env_config.gateway_svid_key_path = Some(path_to_string(&args.svid_key, "--svid-key")?);
    env_config.gateway_svid_trust_bundle_path =
        Some(path_to_string(&args.trust_bundle, "--trust-bundle")?);
    env_config.gateway_spiffe_id = Some(args.spiffe_id);
    env_config.file_config_path = None;

    let opts = ServeOptions {
        proxy_http: Some(proxy_http),
        proxy_https: None,
        admin_http: Some(admin_http),
        admin_https: None,
        admin_jwt_manager: Some(jwt_manager),
        skip_initial_capability_refresh: false,
        background_drain_timeout: Some(Duration::from_secs(5)),
    };

    let (shutdown_tx, _) = watch::channel(false);
    let signal_tx = shutdown_tx.clone();
    tokio::spawn(async move {
        wait_for_shutdown_signal().await;
        let _ = signal_tx.send(true);
    });

    let handles = serve(env_config, config, opts, shutdown_tx)
        .await
        .context("trusted projected file::serve failed")?;
    handles
        .join()
        .await
        .context("HBONE fixture listener failed")?;
    Ok(())
}

fn projected_hbone_config(sidecar_host: &str, sidecar_port: u16) -> anyhow::Result<GatewayConfig> {
    if sidecar_port == 0 {
        bail!("--sidecar-port must be a non-zero TCP port");
    }
    validate_sidecar_host(sidecar_host)?;

    let value = serde_json::json!({
        "version": "1",
        "proxies": [{
            "id": "hbone-edge",
            "name": "hbone edge",
            "namespace": "ferrum",
            "hosts": ["edge.local"],
            "listen_path": "/",
            "backend_scheme": "http",
            "backend_host": sidecar_host,
            "backend_port": sidecar_port,
            "strip_listen_path": false,
            "backend_connect_timeout_ms": 5000,
            "backend_read_timeout_ms": 30000,
            "backend_write_timeout_ms": 30000,
            "upstream_id": "hbone-upstream"
        }],
        "upstreams": [{
            "id": "hbone-upstream",
            "name": "hbone upstream",
            "namespace": "ferrum",
            "algorithm": "round_robin",
            "targets": [{
                "host": sidecar_host,
                "port": sidecar_port,
                "weight": 1,
                "tags": {
                    "mesh.hbone": "true",
                    "mesh.hbone_port": sidecar_port.to_string()
                }
            }]
        }],
        "consumers": [],
        "plugin_configs": []
    });

    let mut config: GatewayConfig =
        serde_json::from_value(value).context("HBONE fixture GatewayConfig must deserialize")?;
    config.normalize_fields();
    Ok(config)
}

fn validate_sidecar_host(host: &str) -> anyhow::Result<()> {
    if host.parse::<std::net::IpAddr>().is_ok() {
        return Ok(());
    }
    let valid = !host.is_empty()
        && host.len() <= 253
        && host
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '.' || c == '-');
    if valid {
        return Ok(());
    }
    bail!("invalid --sidecar-host");
}

fn validate_identity_paths(args: &Args) -> anyhow::Result<()> {
    for (flag, path) in [
        ("--svid-cert", &args.svid_cert),
        ("--svid-key", &args.svid_key),
        ("--trust-bundle", &args.trust_bundle),
    ] {
        if !path.is_file() {
            bail!("{flag} is not a readable file");
        }
    }
    if args.spiffe_id.trim().is_empty() || !args.spiffe_id.starts_with("spiffe://") {
        bail!("--spiffe-id must be a SPIFFE URI");
    }
    Ok(())
}

fn require_private_backend_allow_ips() -> anyhow::Result<()> {
    match std::env::var("FERRUM_BACKEND_ALLOW_IPS") {
        Ok(value) if value == "private" => Ok(()),
        _ => bail!("HBONE fixture requires FERRUM_BACKEND_ALLOW_IPS=private"),
    }
}

fn path_to_string(path: &Path, flag: &str) -> anyhow::Result<String> {
    path.to_str()
        .map(ToOwned::to_owned)
        .with_context(|| format!("{flag} must be valid UTF-8"))
}

async fn bind_loopback(port: u16) -> anyhow::Result<TcpListener> {
    if port == 0 {
        bail!("listener port must be non-zero (ephemeral bind is not part of this fixture)");
    }
    let addr = SocketAddr::from(([127, 0, 0, 1], port));
    TcpListener::bind(addr)
        .await
        .with_context(|| format!("bind {addr}"))
}

async fn wait_for_shutdown_signal() {
    let ctrl_c = tokio::signal::ctrl_c();
    #[cfg(unix)]
    {
        use tokio::signal::unix::{SignalKind, signal};
        let mut sigterm = match signal(SignalKind::terminate()) {
            Ok(s) => s,
            Err(err) => {
                tracing::error!("failed to register SIGTERM handler: {err}");
                return;
            }
        };
        tokio::select! {
            _ = ctrl_c => {
                tracing::error!("SIGINT received, initiating fixture shutdown");
            }
            _ = sigterm.recv() => {
                tracing::error!("SIGTERM received, initiating fixture shutdown");
            }
        }
    }
    #[cfg(not(unix))]
    {
        let _ = ctrl_c.await;
        tracing::error!("Ctrl+C received, initiating fixture shutdown");
    }
}
